### ISSUE TITLE
Test case to check if a method was called in `mounted` hook fails, when stubbed using `jest.fn()`

### ISSUE THREAD

**Issue by kanteankit** [vuejs/vue-test-utils#1027]
### Version
1.0.0-beta.25

### Reproduction link
[https://codesandbox.io/s/rw83wwvzym](https://codesandbox.io/s/rw83wwvzym)

### Steps to reproduce
- Create a Vuejs component having a method and call that method in the `mounted` hook
- In your test case, `shallowMount` the component and stub the `method` using `jest.fn()`
- Write a test case that checks if the method was called using `toBeCalled()`

### What is expected?
The test case should pass

### What is actually happening?
The test case fails with the error message
```
jest.fn() value must be a mock function or spy.
Received:
  function: [Function bound ]
```

**Comment by eddyerburgh** [comment]
Vue binds methods when it adds them to an instance, so the method on an instance is not a reference to the original function. You can solve your issue by keeping a reference to the original function:

```js
it('calls testMethod on mount', () => {
  const testMethod = jest.fn()
  const wrapper = shallowMount(List, {
    methods: {
      testMethod
    }
  })

  expect(testMethod).toBeCalled()
});
```

**Comment by redeemefy** [comment]
I'm having a similar issue here.

`"@vue/test-utils": "^1.0.0-beta.25"`
`"jest": "^23.6.0"`
`"vue-jest": "^2.6.0"`
MacOS: `10.14.2 (18C54)`

The failing message I'm getting is 

```
● AccountsFetchAccounts › methods › fetchAccountName()

  expect(jest.fn())[.not].toHaveBeenCalled()

  jest.fn() value must be a mock function or spy.
  Received:
    function: [Function bound mockConstructor]
```

```
const localVue = createLocalVue();
let wrapper;
let methods = {
  fetchAccountName: jest.fn(() => 'Empty'),
  fetchChildAccountsData: jest.fn(),
};
let computed = {
  instance: jest.fn().mockReturnValue({post: jest.fn(), get: jest.fn()}),
  accountId: jest.fn().mockReturnValue(1)
};
function shallowMountComponent() {
  return shallowMount(AccountsFetchAccounts, {
    localVue,
    methods,
    computed,
  });
}

describe('methods', () => {
  let spy;
  it('created() should get called when component mounts.', () => {
    spy = jest.spyOn(AccountsFetchAccounts, 'created');
    wrapper = shallowMountComponent();
    expect(spy).toHaveBeenCalled();
    spy.mockReset();
  });
  it('fetchAccountName() its been called.', () => {
    let { vm } = shallowMountComponent();
    vm.fetchAccountName();
    expect(vm.fetchAccountName).toHaveBeenCalled();
    // setTimeout(() => {
    // });
  });
});
```
The first test passes fine. I'm having problems with the second test though. If I take the `expect(vm.fetchAccountName).toHaveBeenCalled();` and put it inside the `setTimeout()` the test pass, outside the `setTimeout()` doesn't pass. I did try the following without success. I'm trying to figure this out but can't get it to work without `setTimeout()`. Any help is appreciated.

```
it('fetchAccountName()', async () => {
  let { vm } = shallowMountComponent();
  await vm.fetchAccountName();
  expect(vm.fetchAccountName).toHaveBeenCalled();
  // setTimeout(() => {
  // });
});
```

**Comment by cchooley** [comment]
It seems that deprecating the ability to set methods has made the upvoted answer above an approach that has ceased to work. Is there a new way to test logic in lifecycle hooks?

**Hook in component**
```
private mounted(): void {
    this.getStuff();
}
```

**Test (not working, obviously, but an example of what I'm trying to test)**
```
  it("getStuff() is called on mounted", () => {
    const getStuff = jest.fn();
    wrapper = mountFunction();
    expect(getStuff).toBeCalled();
    wrapper.destroy();
  });
```

**Comment by trainoasis** [comment]
> Vue binds methods when it adds them to an instance, so the method on an instance is not a reference to the original function. You can solve your issue by keeping a reference to the original function:
> 
> ```js
> it('calls testMethod on mount', () => {
>   const testMethod = jest.fn()
>   const wrapper = shallowMount(List, {
>     methods: {
>       testMethod
>     }
>   })
> 
>   expect(testMethod).toBeCalled()
> });
> ```
What about this?

`[vue-test-utils]: overwriting methods via the `methods` property is deprecated and will be removed in the next major version. There is no clear migration path for the `methods` property - Vue does not support arbitrarily replacement of methods, nor should VTU. To stub a complex method extract it from the component and test it in isolation. Otherwise, the suggestion is to rethink those tests.`

**Comment by afontcu** [comment]
Hi! The original comment was posted on 15 Nov 2018, more than two years ago. The deprecation message offers a couple of alternatives to overriding methods directly.

**Comment by nextmat** [comment]
> Hi! The original comment was posted on 15 Nov 2018, more than two years ago. The deprecation message offers a couple of alternatives to overriding methods directly.

The suggestions make sense for a lot of uses of method replacement, but how do they apply to this use case? 

If your goal is to verify that something is called a certain way by `mounted()` is the idea to move that logic to a global injection should can [mock](https://vue-test-utils.vuejs.org/api/options.html#mocks) the injection? That seems like unnecessary overhead for a lot of simple tests.

I'm not sure how to "rethink" a test that is just checking whether `mounted()` executes some expected behavior? Check the state of some data or props after running to verify? This also seems overly complex in some cases.

If anyone has a simple code example of the best way to handle this post-deprecation it would be greatly appreciated. :-)

**Comment by phillt** [comment]
I'm trying to do the same thing here too. I suppose testing the template for renders and testing a method to make sure it called something can be separated into two different tests. I think, at least in my case, this makes sense. I'll report back as soon as I figure out how to "extract a method" from the vue component.

If anyone here knows how to "extract" a method, would you be so kind as to post an example of how to extract `mounted()` from there? Thanks!

**Comment by phillt** [comment]
Okay, so here's what I did:
```javascript
it("It gets monthly report when mounted.", function () {
        const getMonthlyReport = sinon.stub();
        const { mounted } = MonthlyReport;
        const sampleComponent = {
            mounted,
            getMonthlyReport
        }
        sampleComponent.mounted();
        assert(getMonthlyReport.called);
});
```

A few things to know about what is happening here.

- `getMonthlyReport` is actually being provided by a mixin, but since I'm not testing the mixing here, I'm just going to stub the method it provides.
- Since I'm not testing for the application of the context, I don't really need anything fancy. My test is just making sure that we are calling the right method to load data into the component. So I extract the `mounted()` method from the MonthlyReport component, slap it in a new object that contains the `getMonthlyReport` method in the same context.
- assert that `getMonthlyReport` was called and that's it.
