### ISSUE TITLE
Unexpected behaviour when composing components and root element is a component

### ISSUE THREAD

**Issue by Aferz** [vuejs/vue-test-utils#1089]
### Version
1.0.0-beta.28

### Reproduction link
[https://codesandbox.io/s/lx2r4qv33l](https://codesandbox.io/s/lx2r4qv33l)

### Steps to reproduce
Check the codesandbox. (Console)

### What is expected?
I need to check the value set in `to` prop for the `Layout` component.

### What is actually happening?
The `Page` component sets `to` prop for `Layout` component, but is not possible to test because `wrapper.props()` returns `{}` and `wrapper.attributes()` returns `{ to: [Object object] }`

---
Is highly possible that I'm misunderstanding some basic functionality. In that case, how could I test the value of `to` prop is correctly set from `Page`?

Thanks

**Comment by Aferz** [comment]
After some deep research I've found this issue that may be related to current one.

https://github.com/vuejs/vue-test-utils/issues/640

If that is the case, feel free to close this.

Cheers.

**Comment by eddyerburgh** [comment]
This is different to that issue. The confusing behavior is because `props` returns the props of the root instance (Page), but `attributes` returns the attributes of the root DOM element, which is the Layout stub. If you get a wrapper of Layout, by calling `find` with Layout as a selector, you will get the expected behavior:

```js
wrapper.find(Layout).props()
```
