### ISSUE TITLE
Component references in computed property don't match test

### ISSUE THREAD

**Issue by ffxsam** [vuejs/vue-test-utils#1148]
### Version
1.0.0-beta.29

### Reproduction link
[https://codesandbox.io/s/1yy71j858q](https://codesandbox.io/s/1yy71j858q)

### Steps to reproduce
1. Run tests

### What is expected?
1. Test should pass

### What is actually happening?
This is difficult to explain, but the test is failing, even though the proper event is being emitted, and it's causing values to change which trigger the computed property to re-run. But the values themselves are incorrect and don't match those in the unit test itself.

```js
    console.log(
      'inside test, dirty/required:',
      wrapper.vm.$v.email.$dirty,
      wrapper.vm.$v.email.required
    );
```

The results here are `true` and `false` as expected, though the computed property shows `false` and `false` even after the blur event is emitted.

**Comment by eddyerburgh** [comment]
This is a bug with `sync` mode.

To fix your example, set `sync` to false:

```js
const wrapper = mount(HelloWorld, { sync: false })
```

Sync mode will be removed in the next beta version because of these kinds of bugs—[see this issue for more details](https://github.com/vuejs/vue-test-utils/issues/1137).

This bug will be fixed by removing sync mode (which is already in the dev branch), so I'll close this issue.

**Comment by ffxsam** [comment]
Perfect, thank you!
