### ISSUE TITLE
vue-test-utils can not resolve PascalCase names of components

### ISSUE THREAD

**Issue by Qvatra** [vuejs/vue-test-utils#1232]
### Version
1.0.0-beta.29

### Reproduction link
[https://github.com/bootstrap-vue/bootstrap-vue/issues/3270](https://github.com/bootstrap-vue/bootstrap-vue/issues/3270)

### Steps to reproduce
Access a bootstrap-vue component by name: wrapper.find({ name: 'bFormRadioGroup' }).
bootstrap-vue version v2.0.0-rc.19

### What is expected?
wrapper of the element should be returned

### What is actually happening?
empty wrapper is returned

[vue-test-utils]: find did not return Component, cannot call props() on empty Wrapper

---
Per the Vue style guide, since version 2.0.0-rc.12 bootstrap-vue team have named all components using PascalCase instead of camelCase

**Comment by lmiller1990** [comment]
I see two solutions for this:

1. we automatically try matching against pascal/camel/kebab/whatever
2. we only match against the exact name

I'm thinking (1), we should make it as easy as possible to use `find`. It's hard to know what the `name` is for third party components. Since we support the `find({ name })` syntax, we should match Vue and handle both pascal case and kebab case. You would update [this](https://github.com/vuejs/vue-test-utils/blob/ee09270172995884934036aea5ed8e280e888354/packages/test-utils/src/find-dom-nodes.js#L12) file.
