### ISSUE TITLE
TypeError: this.$el.computedStyleMap is not a function

### ISSUE THREAD

**Issue by dewalibaidya** [vuejs/vue-test-utils#1281]
### Version
1.0.0-beta.29

### Reproduction link
[https://jsfiddle.net/dbaidya/7maqgv68/1/](https://jsfiddle.net/dbaidya/7maqgv68/1/)

### Steps to reproduce
Run jest and it shows TypeError: this.$el.computedStyleMap is not a function

### What is expected?
this.$el
        .computedStyleMap()
        .get('font-size')
        .toString()

should pass in jest

### What is actually happening?
this.$el
        .computedStyleMap() is failing in jest.
TypeError: this.$el.computedStyleMap is not a function

**Comment by dewalibaidya** [comment]
any update on this issue

**Comment by aholzner** [comment]
The provided jsfiddle doesn't contain any tests. Could you please provide your tests?

**Comment by JessicaSachs** [comment]
Going to close this as `wontfix` as this is an issue with jsdom and is usually fixed by the user in mocks/stubs. See the links below for additional info.

Because `computedStyleMap` is an experimental feature supported on Chrome and Opera only ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/computedStyleMap)), JSDom has decided not to polyfill this method on `Element`. If you must test code that uses this feature, please follow the [jest guide to implementing methods missing from JSDom](https://jestjs.io/docs/en/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom).

In the future, if you want to check if JSDom supports something, you might find the following code snippet to be helpful

```js
const jsdom = require("jsdom");
const { JSDOM } = jsdom;
const dom = new JSDOM(`<!DOCTYPE html><p>Hello world</p>`);
dom.window.document.querySelector("p") // the Element

// testing if `computedStyleMap` is in JSDom's implementation of Element...
dom.window.document.querySelector("p").computedStyleMap // undefined
```

Hope this helps!

**Comment by vaibhavagrawal2912** [comment]
This method is no more experimental as per MDN: https://developer.mozilla.org/en-US/docs/Web/API/Element/computedStyleMap

Are there any plans to integrate the same in jsdom?

**Comment by DanKaplanSES** [comment]
@vaibhavagrawal2912 You should ask your question in the [JSDOM repository](https://github.com/jsdom/jsdom/). This is the `vue-test-utils` repository. That said, `computedStyleMap` is not supported in Firefox yet, so the feature request will probably be low priority to them.
