### ISSUE TITLE
something wrong slots and scopeSlots ? 

### ISSUE THREAD

**Issue by xxbld** [vuejs/vue-test-utils#1327]
### Version
1.0.0-beta.29

### Reproduction link
[https://github.com/vuejs/vue-test-utils/issues/1326](https://github.com/vuejs/vue-test-utils/issues/1326)

### Steps to reproduce
```js
describe('aaa', () => {
  const Com = Vue.extend({
    render(h) {
      return h('div')
    }
  })
  const wrapper = mount({
    render(h) {
      return h(Com, { ref: 'com' },'aaa')
    }
  })
  it('wrapper.vm.$refs.com.$scopedSlots:', () => {
    // wrapper.vm.$refs.com.$scopedSlots: {default:[Function]} ??????
    console.log("wrapper.vm.$refs.com.$scopedSlots:", wrapper.vm.$refs.com.$scopedSlots)
    // wrapper.vm.$refs.com.$slots: {default:[VNode]}
    console.log("wrapper.vm.$refs.com.$slots:", wrapper.vm.$refs.com.$slots)
    
  })
})
```

### What is expected?
$scopedSlots.default ===undefined

### What is actually happening?
$scopedSlots: {default:[Function]}

**Comment by vvanpo** [comment]
This isn't a `@vue/test-utils` issue, and is descibred in the Vue API documentation: https://vuejs.org/v2/api/#vm-scopedSlots

> All $slots are now also exposed on $scopedSlots as functions.

**Comment by vvanpo** [comment]
I don't think this is a problem with `@vue/test-utils`. Try the following, with dependencies only on `Vue`:

```js
describe('aaa', () => {
  const Com = Vue.extend({
    render(h) {
      return h('div')
    }
  })
  const vm = new Vue({
    render(h) {
      return h(Com, { ref: 'com' },'aaa')
    }
  }).$mount()

  it('should not have a slot', () => {
    expect(vm.$refs.com.$slots).toEqual({})
      // Fails, the `$slots` object contains a `default` property.
  })
})
```

**Comment by vvanpo** [comment]
Because you're explicitly passing in a child node (the text `aaa`), even though `Com` does not declare a slot (and hence the text node won't be rendered) the node is still registered in `$slots`.

I believe this is expected behaviour, and not a bug: https://vuejs.org/v2/guide/render-function.html#Basics

> In this case, you have to know that when you pass children without a v-slot directive into a component, like the Hello world! inside of anchored-heading, those children are stored on the component instance at $slots.default.

Without passed children populating `$slots.default` (and `$scopedSlots.default` by extension), render functions wouldn't be able to make use of slots.

The linked issue claims this behaviour is different in the browser, but I can confirm that it is not: https://codesandbox.io/s/vue-template-lcunb

In `App.vue`, you can see that the template for `Test` does not provide any slots. But `App` passes text nodes into the default slot, and the `bar` slot. Neither of these slots are rendered in the browser, but both are logged to the console.

**Comment by xxbld** [comment]
@vvanpo 
just `$scopedSlots` wrong  in jest environment;
in bowser everything is ok;

**Comment by xxbld** [comment]
> @vvanpo
> just `$scopedSlots` wrong in jest environment;
> in bowser everything is ok;

bowser this.$scopedSlots.default=undefined
jest this.$scopedSlots.default=function

**Comment by vvanpo** [comment]
@xxbld My sandbox example (https://codesandbox.io/s/vue-template-lcunb) contradicts that, it logs the child element's `$slots` and `$scopedSlots` to the console, and they are not undefined. Feel free to fork it and provide a reproduction.

**Comment by xxbld** [comment]
thanks for your answer.  it`s my fault.

my code  outdate
```js
render(){
if(this.$scopedSlots.default)
   // render default
}else if(this.props.renderProp){
  // renderProp
}else{
  // render $slots.default
}
```

https://vuejs.org/v2/api/#vm-scopedSlots
> All $slots are now also exposed on $scopedSlots as functions. If you work with render functions, it is now recommended to always access slots via $scopedSlots, whether they currently use a scope or not. This will not only make future refactors to add a scope simpler, but also ease your eventual migration to Vue 3, where all slots will be functions.
