### ISSUE TITLE
Is this library still maintained? 

### ISSUE THREAD

**Issue by gplusdotgr** [vuejs/vue-test-utils#1329]
### What problem does this feature solve?
Latest release on February, many open PRs, issue requests.. It's a core library, and it's getting probably the least amount of attention. How can we build production grade applications without a reliable testing library? 

### What does the proposed API look like?
 It's a core library, and it's getting probably the least amount of attention. How can we build production grade applications without a reliable testing library?

**Comment by rnicholus** [comment]
Should we consider forking this project and lining up a team of maintainers to continue to evolve that fork? Or is there a viable option that keeps this here without it continuing to decay?

**Comment by gplusdotgr** [comment]
Let's. I tried contacting many core members, didn't get any replies. Everyone seems focused on 3.x and the Compose API.

**Comment by winniehell** [comment]
@yyx990803 @eddyerburgh Can you please comment?

**Comment by tbsvttr** [comment]
> How can we build production grade applications without a reliable testing library?

I am asking that myself! At the moment I see this as the biggest problem of the Vue ecosystem.

**Comment by rnicholus** [comment]
No response and no .30 beta release. Seems like this will have to be forked. Any thoughts on where to fork and who might maintain this?

**Comment by gterras** [comment]
A project of this kind is pretty much doomed if not maintained by core team. Let's hope Vue 3 release will bring more attention to `vue-test-utils` (and `vue-dev-tools` since we're at it).

**Comment by eddyerburgh** [comment]
Sorry for the silence, I haven't been checking my notifications the last two months for personal reasons. 

I'm no longer able to give this project enough time, and so I'm stepping down as maintainer. It's taken me a few months to come to this decision, but as you point out, I haven't even active since the beginning of this year.

There's lots of interest in keeping the project alive, and I'm contacting possible maintainers, so we should be able to keep this project going. 

In the mean time, if anyone else wants to help with Vue Test Utils you can:

* Triage issues
* Review pull requests
* Open pull requests for bug fixes

**Comment by vvanpo** [comment]
@eddyerburgh sorry to hear that you have to step down, we appreciate all the work you've put into this project.

When opening pull requests, is there a list of contributors with merge permissions that we can poke for reviews?

**Comment by dobromir-hristov** [comment]
I will close this for now as we are trying to reduce unnecessary issues. The project will not go unmaintained :)
