### ISSUE TITLE
Watcher for mocked global property doesn't fire

### ISSUE THREAD

**Issue by Marcelinka** [vuejs/vue-test-utils#1450]
### Version
1.0.0-beta.31

### Reproduction link
[https://github.com/Marcelinka/vue-test-utils-watcher-bug](https://github.com/Marcelinka/vue-test-utils-watcher-bug)

### Steps to reproduce
1. Clone repository
2. In console run command `yarn install`
3. In console run command `yarn test`

### What is expected?
Test will be passed

### What is actually happening?
Test failed

---
I have global property for size of screen from package vue-mq. And I have watcher for this global property to add or remove event listener on scroll. When I try to test that addEventListener or removeEventListener are fired, I see that problem.

I try to set it by `wrapper.vm.$mq = 'sm'`,  I try to use setData, I try to wait for nextTick (or flushPromises), it doesn't work.

**Comment by LinusBorg** [comment]
The `$mq` mock does no create a reactive data property (and it's not supposed to), so the watcher can't watch it. So this behaviour is expected.

Since you left out the actual implementation of `$mq` in your reproduction I can't recommend other approaches.

**Comment by lmiller1990** [comment]
This won't work since `watch` only works on reactive properties, and what you are doing with mocks is setting a static value (not part of Vue's reactive system). edit: @LinusBorg is too quick!

You could try using `localVue` and installing the [actual plugin](https://github.com/AlexandreBonaventure/vue-mq#usage) and going from there.

**Comment by Marcelinka** [comment]
This package counts width of screen and give me a breakpoint, but in unit-tests no screen and no width. That will be complicated to change it's value with functionality of package. And I need to test only watcher, but not this package. I don't really understand what you propose. Can you give me example, please?

**Comment by Marcelinka** [comment]
Besides, why exactly mock property can't be reactive? I think it'll be useful for cases, when we use it in computed properties or watch for it.

**Comment by Marcelinka** [comment]
Maybe we can do special method, like setMocks, that can force rerendering?

**Comment by lmiller1990** [comment]
I was able to make this work. You can make something reactive by calling `Vue.observable`. Here is the code: 

```js
import Vue from 'vue'
import TestComponent from "./TestComponent.vue";
import { shallowMount } from "@vue/test-utils";

it('Test firing watcher for mocked global property', async () => {
  const mock = jest.fn()
  global.window = Object.create(window);
  Object.defineProperty(window, 'removeEventListener', {
    value: mock
  });

  const wrapper = shallowMount(TestComponent, {
    mocks: {
      $mq: Vue.observable({ val: 'md' })
    }
  })

  wrapper.vm.$mq.val = 'lg'
  await wrapper.vm.$nextTick()
  expect(window.removeEventListener).toHaveBeenCalled()
});
```

```vue
<template></template>

<script>
export default {
  watch: {
    $mq: {
      handler() {
        console.log('Watching')
        window.removeEventListener('scroll', this.resizeHeader);
      },
      deep: true
    }
  }
}
</script>
```

I had to add `deep: true` since `$mq` is an object, not a primitive value - I'm not sure if this is helpful to you.

The test deals with a lot of browser specific things that are not really applicable in the test environment (which uses jsdom, a headless browser, so it doesn't handle things like resizing) so I'm not sure how valuable writing a unit test for this feature is. For now, this is the best I could do. Hopefully you find this useful.

I don't know how much sense to make `mocks` reactive, since you can just use `Vue.observable`. There might be a use case where someone does not want their mock to be reactive.
