### ISSUE TITLE
Stubs not working in functional component mounted with shallowMount

### ISSUE THREAD

**Issue by enriqg9** [vuejs/vue-test-utils#1522]
### Version
1.0.0-beta.31

### Reproduction link
[https://github.com/enriqg9/test-utils-functional-component-stub](https://github.com/enriqg9/test-utils-functional-component-stub)

### Steps to reproduce
In the example below, shallowMount does not stub the HelloWorld child component if the parent is a functional component.

```javascript
import {shallowMount} from '@vue/test-utils'
import HelloWorld from '../../src/components/HelloWorld'

const functionalComponent = {
  functional: true,
  name: 'FunctionalComponent',
  render(h) {
    return h(HelloWorld)
  }
}

const exampleComponent = {
  name: 'ExampleComponent',
  render(h) {
    return h(HelloWorld)
  }
}

describe('HelloWorld.vue', () => {
  it('stubs the children of components mounted with shallowMount', () => {
    const wrapper = shallowMount(exampleComponent)
    expect(wrapper.find('helloworld-stub').exists()).toBeTruthy() // Passes
  })

  it('should stub children of functional components mounted with shallowMount', () => {
    const wrapper = shallowMount(functionalComponent)
    expect(wrapper.find('helloworld-stub').exists()).toBeTruthy() // Fails
  })
})
```

### What is expected?
`shallowMount` should stub the child components

### What is actually happening?
`shallowMount` is not stubbing the child components if the parent is a functional component

---
Maybe this is intended? If so, how should I unit test that the functional component is creating the proper child component?

**Comment by dobromir-hristov** [comment]
Cant you just use mount? You can find the component and assert with `.is()`?

I am sorry but stubs in VTU-beta are pretty buggy, as you can see.

**Comment by enriqg9** [comment]
@dobromir-hristov Still the same result, the component does not get stubbed.

**Comment by dobromir-hristov** [comment]
Can you provide a manual stub via `stubs` option?

**Comment by enriqg9** [comment]
@dobromir-hristov  Does not seem to be working either, now the example component is not stubbing either. I've used manual stubs before and they worked fine but not sure if the component calling the `render` function has something to do with it. 

Logging `wrapper.html()` shows the output for the `HelloWorld` component and not the stub.

```javascript
  it('stubs the children of components mounted with shallowMount', () => {
    let HelloWorld = {
      name: 'HelloWorld',
      render: (createElement) => createElement('div', {class: 'helloworld-stub'})
    }

    const wrapper = mount(exampleComponent, {
      stubs: {
        HelloWorld: HelloWorld
      },
    })
    
    expect(wrapper.find('.helloworld-stub').exists()).toBeTruthy() // Fails
  })

  it('should stub children of functional components mounted with shallowMount', () => {
    let HelloWorld = {
      name: 'HelloWorld',
      render: (createElement) => createElement('div', {class: 'helloworld-stub'})
    }

    const wrapper = mount(functionalComponent, {
      stubs: {
        HelloWorld: HelloWorld
      },
    })

    expect(wrapper.find('.helloworld-stub').exists()).toBeTruthy() // Fails
  })
```

**Comment by lmiller1990** [comment]
The last example (above post) it working fine for me - is it possible you wrote that example with the `HelloWorld.vue` default component imported as well (in `example.spec.js`)?

Eg this is passing:

```js
import {shallowMount, mount} from '@vue/test-utils'
// import HelloWorld from '../../src/components/HelloWorld' <- commented this out

it('stubs the children of components mounted with shallowMount', () => {
  let HelloWorld = {
    name: 'HelloWorld',
    render: (createElement) => createElement('div', {class: 'helloworld-stub'})
  }

  const exampleComponent = {
    name: 'ExampleComponent',
    render(h) {
      return h(HelloWorld)
    }
  }

  const wrapper = mount(exampleComponent, {
    stubs: {
      HelloWorld: HelloWorld
    },
  })

  expect(wrapper.find('.helloworld-stub').exists()).toBeTruthy() // Fails
})
```

**Comment by lmiller1990** [comment]
Interestingly enough this is also failing:

```js
  const functionalComponent = {
    name: 'FunctionalComponent',
    render(h) {
      return h(HelloWorld)
    }
  }

  it('should stub children of functional components mounted with shallowMount', () => {
    const wrapper = mount(functionalComponent, {
      stubs: {
        HelloWorld: true
      }
    })

    expect(wrapper.find('helloworld-stub').exists()).toBeTruthy() // Fails
  })
```

But this passes:

```js
  const functionalComponent = {
    components: { HelloWorld },
    name: 'FunctionalComponent',
    template: '<div><hello-world /></div>'
  }
```

No  functional component - just a render function. Seems like the bug is related to render functions, not functional components (obviously functional components have render functions, which is why they exhibit this problem).

Unlikely to fix your immediately problem, but if you are interested you could try VTU next (for Vue 3) which handles stubs much better.

**Comment by enriqg9** [comment]
@lmiller1990 Yeah apparently this is something related to the render function. I tried commenting the component but it is still failing. 

In my real world application I want to stub a component that interacts with Vuex and with either shallowMount or passing a custom stub to Mount I get `[Vue warn]: Error in render: "TypeError: Cannot read property 'state' of undefined"`. I know I can mock the $store but my test would be getting polluted by a child component. 

I am not familiar with Vue 3 yet, will start getting familiar with it and give it a try.

**Comment by lmiller1990** [comment]
Basically Vue 3 == Vue 2, but some extra stuff with some some changes. 

The problem is the ecosystem has not caught up - understandable that people don't want to use it in production yet.

I am not sure how to solve this one, the stubbing logic is very convoluted. I will let you know if I think of anything, I don't expect to solve this any time soon, though. Hate to say it but the only work-around I see as of how are 

1. do not use a functional component. I don't consider this acceptable. I don't change my prod app since the testing library is not working.
2. which means the alternative is don't stub out the component. What is the exact situation that requires you to use a stub? If you can explain it, I can potentially share some alternatives (such as `mocks`).

If you are using jest, you can "stub" a component like this:

```
jest.mock('../Hello.vue, () => ({
  template: '<div>Mock it out</div>'
}))
```

^^^^ Untested but you get the idea. I wrote about it [here](https://lmiller1990.github.io/vue-testing-handbook/vue-router.html#workaround-for-large-render-trees-using-mount).

The reason I like to use `jest.mock` instead of `stubs` is `stubs` messes with Vue's rendering internals,  which feels bad to me. I strongly dislike it when testing libraries mess with production code internals to achieve things, since it can (and does) have weird side effects, like you observed.

I feel like we need a "Vue Test Utils: the good parts".

**Comment by enriqg9** [comment]
@lmiller1990 Thanks, I used jest to mock the component as you show and that seems like a good solution for now.
