### ISSUE TITLE
Test slot scope

### ISSUE THREAD

**Issue by Akryum** [vuejs/vue-test-utils#156]
We should add a way to test the scoped slots. For example, `<slot v-for="..." :item="item" :index="index" />` ➡️ We should be able to test the values of  `item` and `index` in the slot.

**Comment by LinusBorg** [comment]
ok so there's two problems:

1. creating a proper scopeSlot Function
2. adding the scoped slots content to the vm.

### 1. creating a proper scopeSlot Function

For normal slots, vue-test-utils uses `vue-template-compiler`, which still have some limitations.

My suggestion would be to use a real Vue instance instead to create the slot content:
```javascript
function createSlotContent ({
  slotValue: string,
  slotName: string = 'default',
  scoped: Boolean = false
}) : Function | Array<VNode> {
  const slotParent = new Vue({
    components: {
      slotter: { template: `<div></div>`},
    }
    template: `<div><slotter ref="slotter">${slotValue}</slotter></div>`,
  })
  return slotParent.[scoped ? '$scopedSlots' : '$slots'][slotName]
}
```

### 2. adding the scoped slots content to the vm.

For normal slots, we simply do `vm.$slots = slotContent`, but that doesn't work for $scopedSlots because of [this line](https://github.com/vuejs/vue/blob/956756b1be7084daf8b6afb92ac0da7c24cde2a5/src/core/instance/render.js#L74) in the `vm._render` function:
```javascript
if (_parentVnode) {
      vm.$scopedSlots = _parentVnode.data.scopedSlots || emptyObject
    }
```
This code will run everytime we (re-)render the vm, and since there isn't an actual parentVnode to read scoped slots from, we would have to mock it.

That must be tested extensively, I guess.

**Comment by eddyerburgh** [comment]
Adding a parent node would solve another problem we're having with `$attrs`. I think this could be a good solution.

I'll look into it.

**Comment by LinusBorg** [comment]
Great! I'll also take a look between the holidays if I have an hour or two.

**Comment by jorySsense** [comment]
Is there anything I can do to help with this?

**Comment by 38elements** [comment]
I try to resolve this issue.
I will send pull request within 3 days.

**Comment by eddyerburgh** [comment]
@38elements That would be great! We were thinking about creating a parent instance inside the create-instance method, like  @LinusBorg suggested.

**Comment by 38elements** [comment]
@eddyerburgh 
Since I am unsure of whether my implementation method is correct,
I sent a pull request of incomplete code.
It is #507 . 
I think it resolve to replace the [renderSlot](https://github.com/vuejs/vue/blob/5a9da95b8a865416f082952a48416ffc091e4078/src/core/instance/render-helpers/render-slot.js#L8) method.

**Comment by eddyerburgh** [comment]
This has been added in #507 and will be released in beta.15

**Comment by smiller171** [comment]
@eddyerburgh is there a target release date for beta 15? I'm trying to finally start doing TDD and not being able to test scoped slots is blocking that. I tried building myself but no luck so far.

**Comment by eddyerburgh** [comment]
@smiller171 Yes, I'll release on Monday evening

**Comment by smiller171** [comment]
Thanks for the quick response @eddyerburgh!

I managed to get my own copy running too, so I've got a stopgap.
