### ISSUE TITLE
Mock method in stubbed child component

### ISSUE THREAD

**Issue by ol1s** [vuejs/vue-test-utils#1570]
### Feature Description

Is there a way to mock a method from a stubbed child component without having to deep mount?

### Problem

I have a ParentComponent which fires a method on a ChildComponent by using the `$refs` property. However, in testing when I shallowMount the ChildComponent, the method doesn't exist on the stub. Is there a way for me to mock this?

```
//ParentComponent.vue
export default {
  components: {
    ChildComponent
  },
  methods: {
    validate () {
      this.$refs.child.validate()
    }
  }
}

<template>
  <ChildComponent ref="child" />
</template>

//ChildComponent.vue
export default {
  methods: {
    validate () {
      this.$emit('errors', false)
    }
  }
}

//ParentComponent.test.js
describe('ParentComponent', () => {
  it('validates child component', () => {
    const parent = shallowMount(ParentComponent)
    const child = parent.find(ChildComponent)    <----- this will be a stubbed component
    parent.vm.validate()                         <----- how do we mock the child.validate() method
    expect(child.emitted('errors')).toBeTruthy()
  })
})
```

### Expected behaviour

I should expect to be able to define in my test what output will be provided if a method on a stubbed component is called.

### Alternatives

Using `mount()` as opposed to `shallowMount()` solves the issue, but also means cannot test the ParentComponent as a separate unit to the ChildComponent.

**Comment by lmiller1990** [comment]
Ideally you should use `mount`. You could try using a custom stub, something like:

```js
mount(Parent, {
  stubs: {
    Child: {
      template: '<div />',
      methods: {
        validate: { this.$emit('whatever') }
      }
    }
  }
})
```

I am not sure if this will work with `shallowMount`. It should, though (can't say for sure, I have not tried this with `shallowMount`). Of course, if you change `Child`, the `Parent` test will still pass - this approach often leads to false positives.

For this reason, my personal opinion and strong recommendation is just use mount and test them together - there is no real benefit to testing them in isolation.

Anyway, let me know if that works for you.

**Comment by ol1s** [comment]
Thanks, looks like `mount()` and `shallowMount()` take the same options so may be on the right track....however I get a syntax error when using your example:

```
SyntaxError: Unexpected keyword 'this'
```

When I try and change to a function `validate: function() { ... }` I then get a Vue error:

```
[vue-test-utils]: options.stub values must be passed a string or component
```

**Comment by lmiller1990** [comment]
Ok here is a full example that I just tested. I realized you just want the child to emit and event (right)? So you can do this:

## Foo.vue

```vue
<template>
  <div>
    <Bar @validate="validate" />
  </div>
</template>

<script>
import Bar from './Bar.vue'

export default {
  name: 'Foo',
  
  methods: {
    validate() { console.log('It works') }
  },

  components: {
    Bar,
  } 
}
</script>
```

## Bar

This file does nothing since you stub it anyway. In your example it is "Child".

```vue
<template>
  <div>
  </div>
</template>

<script>

export default {
  name: 'Bar',
}
</script>
```

## Test

```js
import { shallowMount } from '@vue/test-utils'
import Foo from '@/Foo.vue'

describe('Foo.vue', () => {
  it('does stuff', () => {
    const Bar = {
    template: '<div />',
      methods: {
        validate() {
          this.$emit('validate')
        }
      }
    }

    const wrapper = shallowMount(Foo, {
      stubs: {
        Bar
      }
    })

    wrapper.find(Bar).vm.$emit('validate')
  })
})
```

You don't even need the `validate` method in the stub really. Just call `vm.$emit('validate', <stuff here>)`. If you *really* want to call the stubed method you can do `find(Bar).vm.validate` and it works.

Again you are writing a lot of code for very little value - this example illustrates how to do what you asked, but again I cannot recommend this approach to testing. This is Vue Test Utils, not Vue Unit Test Utils - don't be afraid to use it to make sure multiple components are working together correctly :) TDD has a time and place, especially useful for complex business logic, but not sure how much sense it makes for components.

For some more context on why isolation is not always the answer, you can read Kent's [Why I never use shallow rendering](https://kentcdodds.com/blog/why-i-never-use-shallow-rendering), or DHH's less nice but more honest article [TDD is head love live testing](https://dhh.dk/2014/tdd-is-dead-long-live-testing.html).

**Comment by ol1s** [comment]
Thanks @lmiller1990 - my gut feel says shallow mount for unit testing (in isolation), full mount for testing a full feature....but I will read the articles you posted!
