### ISSUE TITLE
vue-test-utils doesn't track object props

### ISSUE THREAD

**Issue by alexey2baranov** [vuejs/vue-test-utils#1621]
### vue-test-utils doesn't track object props

**Context**

i have a `User` object which is the data model for a vue.js UserComponent. When the component is mounted the `user` has undefined fields. Then inside the `mounted() `method the `user` is fetched from the server and all its fields are setted.

**Problem**

So i found that `vue-test-utils` doesn't redraw component when user's fields changed.

**Note**

On the other hand the same test works good if i change object prop `user` to scalar.

### Steps to reproduce
https://github.com/alexey2baranov/vue-test-utils-getting-started

### Expected behaviour

Test should be done

### Actual behaviour

Test fails

### Possible Solution

Unfortunately i don't know any possible solution. I tried to reset user prop by `wrapper.setProp({user: user})` after its fields was fetchad. Unfortunatelly it is impossible as `vue-test-utils` prevent to set the same object to prop twice.

**Comment by syntax-error** [comment]
I've run into a similar issue today. I believe it comes down to the fact that initialising props using `mount({ propsData })` will not place reactivity on any objects within propsData. But using `wrapper.setProps(...)` will place reactivity. This means that if I have the prop `myProp: { a: 12, b: 'hello' }`, and I have a button that goes `myProp.a += 1`, I will not trigger computed or watcher updates if I provided myProp to `mounted`; but I will if I originally provided it via `setProps`.

And you can't say "well just use setProps", because like in the OP's case, we have things happening on created and mounted, by which point it's too late to be using setProps; it wouldn't match how the component functions in the actual application.

**Comment by dobromir-hristov** [comment]
The example you showed mutates the prop, has a promise that you dont await... This is not a VTU issue.

**Comment by alexey-baranov** [comment]
@dobromir-hristov I was very dissapointed that you closed my issue. I suppose this issue clearaly shows VTU bug, I think it must be reopened.  Maybe you have to review it again or I will open it in another one.

I will try to explain this test. You say i don't await `mounted ` promise, but it is not clearaly true. If you see in the code again you can see  `await waitForExpect()`. waitForExpect checks all expectations every 50ms during 5 seconds, which is the default `Jest `timeout. 5seconds-long waitForExpect guarantes that the 1second-long `mounted ` promise resolves before last `waitForExpect ` iteration checks the expectations.

So this test clearaly shows that VTU mounts a component, then the component mutates its object property inside `mounted ` hoock in 1 second, and then the test checks every 50 ms that the VTU redraws component. During this 5 seconds VTU doesn't redraw the component and the test fails.

Maybe you can show me the clearer way of awaiting the `mounted` promise. Then I can refactor my code. But I don't think it changes the test's result.
