### ISSUE TITLE
Trigger event on conditionally empty wrapper

### ISSUE THREAD

**Issue by apathetic** [vuejs/vue-test-utils#1662]
### Subject of the issue

I'm trying to trigger an event on a vue-test-utils wrapper. In my case, the root of the template is a `<transition>`, and the contents may be conditionally shown / hidden using a prop.  If the contents are visible, I can trigger an event (any event, actually).  If they are hidden, I get an error.

### Steps to reproduce

```
  <transition name="fade">
    <div
      v-if="open"
      @keydown.esc="dismiss"
    >
      Hello World
    </div>
  </transition>
```

Trying to get a working example here, but it's just code snippet at the moment:
https://jsfiddle.net/hLmk4b26/7/

### Expected behaviour

I should be able to trigger `events` on a wrapper

### Actual behaviour

I can conditionally trigger events. If the `div` inside a transition is visible, I can trigger events per usual; if it's not rendered, I cannot trigger any event. I don't expect the component to respond to events in this case, but I feel I should still be able to trigger them.

What happens instead?

```
    TypeError: Cannot read property 'length' of undefined
```

### Possible Solution

I'm not 100% sure if this is a reasonable expectation.  I have a suite of tests that click and fire events in different scenarios, but a possible solution might be to only run them in certain cases vs. all cases (ie. if I know `open` is false, say)

**Comment by lmiller1990** [comment]
Hm. I don't think this makes sense. If `open` is `false` the `<div>` will not be rendered - no browser will let you trigger an event on a non-existent DOM element.

If you are using `v-show, you should be able to trigger the event (since there is a node to trigger an event on).

Conversely, if you *could* trigger an event on a non-existent node, this would be a bug - many tests that should fail would potentially passing (evergreen test).

**Comment by apathetic** [comment]
@lmiller1990 thanks - I wasn't sure; while there was no vnode, my expectation was that the `wrapper` still exists and I should be able to interact with it.  I think that makes sense, so I'll close this guy out -
