### ISSUE TITLE
Generally Unlink updated functions from deprecated ones 

### ISSUE THREAD

**Issue by telion2** [vuejs/vue-test-utils#1692]
### Documentation Feedback

e.g. the function "wrapper.find" and "wrapper.get" are linked. 
"**Works just like find but** will throw an error if nothing matching the given selector is found. You should use find when searching for an element that may not exist. You should use this method when getting an element that should exist and it will provide a nice error message if that is not the case."

It would be generally nice to not have those links, as deprecated functions will eventually stop to exist. 
Furthermore I would like to avoid to read and understand deprecated code and accidentially use them. 

My suggestion would also be to put all deprecated features in a separated place and decouple it. 

**Affected documentation page:** Insert a link to the affected page
https://vue-test-utils.vuejs.org/api/wrapper/#get
There are more of those than get though.

**Comment by lmiller1990** [comment]
`get` and `find` will not be deprecated, though.

I think it makes more sense to have all the docs in one place; the deprecation messages are *very* clear. Since most people will be reading the [new docs](https://github.com/vuejs/vue-test-utils-next-docs) in the future, I don't see too much value in doing a major rehaul of these right now.
