### ISSUE TITLE
Guide on testing without a build step has been removed

### ISSUE THREAD

**Issue by matt-auckland** [vuejs/vue-test-utils#1731]
### Documentation Feedback

Hi there, I'm currently trying to add tests to a project that has no build step and it seems like there was a guide for it, but it was deleted.

It's strange because the guide seems to exist in other languages still but the English version was deleted.

https://github.com/vuejs/vue-test-utils/commit/1d9d548057f9c3da7b260b6a2de728b493187dd8#diff-c1786a86aedb05d4bdd9e214f7e7102b33e68d42fdd260827c8b72b949de90d9

Could the guide be restored so people can keep using it? Or was there something wrong with it, so it was better off removed?

**Comment by lmiller1990** [comment]
It removed because this is not something people do very often. It's assumed if you are doing something like this, you know what you are doing - most people will be using Vue CLI or similar. 

The idea was to focus the docs more the API and less on configuring things - these kind of guides are especially hard to maintain with dependencies sand versions constantly changing, and adds more maintenance work for what is already a complex project.

I think this kind of thing is probably better fit for a blog post. If you want to take this, rework it into a post, and post it somewhere, we could add a link to it. At this point I don't want to add more "how to configure" info to the docs. I will close this issue for now.

**Comment by matt-auckland** [comment]
Fair assumption, unfortunately I don't know what I'm doing haha (thus reading this guide), I'm just dealing with some legacy code and trying to see how I can unit test it. 
I'll see if I can hack something together and write a blogpost 😬

**Comment by lmiller1990** [comment]
Good luck, let me know if you need help 👍 

If you are using Jest it should "just work" more or less. It varies test runner to test runner, app to app, thus the difficulty of writing a definitive guide.
