### ISSUE TITLE
Async API like "waitForElementVisible(selector, [timeout])"

### ISSUE THREAD

**Issue by BigYu** [vuejs/vue-test-utils#174]
Perhaps similar to: https://www.npmjs.com/package/enzyme-wait

**Comment by BigYu** [comment]
I dont find how can I do this check for now

**Comment by eddyerburgh** [comment]
I don't think we should add this to vue-test-utils. Waiting for promises/ timeouts to resolve isn't a vue specific problem. I'm happy to discuss this though because a few people have requested a similar feature.

You can wait for promises to resolve using [flush-promises](https://www.npmjs.com/package/flush-promises).

```js
import flushPromises from 'flush-promises'

test('an async component', async () => {
  const wrapper = mount(AsyncComponent)
  await flushPromises()
  wrapper.
})
```

**Comment by BigYu** [comment]
@eddyerburgh Thanks for explaining and I see your points.

I'm using setTimeout/_.defer to work around which seems exactly what flush-promises does.

**Comment by lmiller1990** [comment]
I second this shouldn't be in the core lib. This is a common request - but I think people really asking "how do I do this" rather than "make the feature".

I think the best solution is a guide in the docs how on to deal with async.
