### ISSUE TITLE
setValue should respect maxlength attribute

### ISSUE THREAD

**Issue by dospunk** [vuejs/vue-test-utils#1864]
### Feature Description

It would be nice if `wrapper.setValue` would respect the `maxlength` attribute on inputs if it is present.

### Problem

I am trying to test a credit card input system, and part of the functionality is that it sets the `maxlength` attribute of the card number input element based on the card's type. Because `setValue` does not respect the `maxlength` attribute, there is no good way to test this behavior besides checking the `maxlength` value directly, which errs on the side of testing implementation details in my opinion. 

### Expected behaviour

The following test should pass

```js
test('respect maxlength', async () => {
    const limitedInput = mount(MyVueComponent).find('input[maxlength="5"]');
    await limitedInput.setValue('this is more than 5 characters');
    expect(limitedInput.element.value).toBe('this ');
});
```

### Alternatives

An ideal solution would be to have a more true-to-life way to simulate inputs, but from my research it seems like the maintainers have decided this isn't feasible.

**Comment by OXXXRA** [comment]
This PR will be fix this issue: https://github.com/vuejs/vue-test-utils/pull/2054

**Comment by lmiller1990** [comment]
Hi, sorry we never replied. I don't think this should be supported. I just tried this in a real browser - even with `maxlength`, if you use JS to update `value` (like we do in Test Utils) it'll ignore the maxlength and update the `value`, anyway, so what we are doing here actually does match a real browser.

When you go to submit, if you configured your form correctly, the default browser validation should prevent the form from submitting. What happens when you do that? I'd say this is the most production like way to test - the goal of validating inputs is to prevent a form submission, in general.

If we were simulating real typing, such as with a tool like Cypress, you'd be able to test this. In fact, I'd suspect if you used Cypress Component Testing w/ Vue, it would prevent you from typing more characters. Something like


```js
const Comp = {
  template: `<input maxlength="3" />`
}
cy.mount(Comp)
cy.get('input').type('12345') // should only do 123, I think
```
