### ISSUE TITLE
Add API to trigger lifeCycles manually.

### ISSUE THREAD

**Issue by wxsms** [vuejs/vue-test-utils#1894]
### Feature Description

Some lifecycles are hard to be test in certain cases. For example, I have no idea on how to test `activated` in shallowMount mode,  since `<keep-alive>` will be a stub. Howerver shallowMount is a MUST in my complicated applications.

### Expected behaviour

provide an API like:

```js
// does exacly what it says
// other lifeCycles should work, too.
wrapper.triggerLifeCycle('activated') 
```

my solution for now (which works):

```js
export function triggerLifeCycle(vm, lifeCycle) {
  if (vm.$options[lifeCycle]) {
    vm.$options[lifeCycle].forEach(fn => {
      fn.call(vm);
    });
  }
}
```

if the idea sounds accepatble, I'm glad to make a PR. thanks.

**Comment by bponomarenko** [comment]
@wxsms Maybe you can try to provide actual keep-alive component as explicit stub? Something like:
```js
import Vue from 'vue';

const wrapper = shallowMount(YourComponent, {
  stubs: { KeepAlive: Vue.component('KeepAlive') }
});
```

Didn't try it myself though, so just an idea.

**Comment by wxsms** [comment]
It's just an example. I'd like to have the ability to test whatever I want (for white box purpose) in a convenient way.

**Comment by bponomarenko** [comment]
@wxsms There is one aspect I think which may conflict with the request "to trigger lifeCycles manually". So far wrapper API was providing methods to trigger actions, which usually can be triggered by the Component developers (`setData`, `setProps`, etc.) or by the users (`trigger('click')`, `setChecked()`, etc.). Component lifecycle hooks are different because they are fully controlled by the framework itself, and there is no way to trigger them programmatically from the Component either.
Providing such interface in Vue test utils may pose a few issues:
* it can produce implementation, which is not officially supported and hence it would be hard to maintain it from version to version
* it would allow to emulate situations, which would never normally occur (`mounted` hook is called before element is actually added to the DOM, or it is called multiple times)

I'm not sure what is the official maintainers opinion on this subject, it is just my point of view. When I end up in a similar situation, I usually have couple options:
* use directly built-in Vue components as stubs (as I showed earlier)
* re-organize component code to move all the logic from the lifecycle hook to the method, which can easily be triggered.

So instead of:
```js
export default {
  activated() {
    // ... some logic
  }
}
```
component is refactored to:
```js
export default {
  activated() {
    this.onActivated();
  },
  methods: {
    onActivated() {
      // ... some logic
    },
  },
}
```

This would allow to trigger it by simply calling `wrapper.vm.onActivated()`. Hope this helps.

**Comment by wxsms** [comment]
Thanks for your comment. I understand your concern. I can provide more examples in my case, which is hard to test without manually trigger (or maybe I'm wrong, I have not use this lib for long, but I do read the docs):

1. I'd like to test that a component do something inside the `created` or `mounted` hook. for example, it should call `this.fetchData()` inside. for other lifecycles, I can use spy or mock functions, but the component is mounted or created as soon as wrapper ready. which make it impossible to spy or mock on the vm method. (or possible but I don't know how)
2. as for the refactor solution you provided, It do make sense. But imagine that I want the `fetchData` method to be call exactly in `mounted` hook, not `created` or any other, how can I ensure that for now? In other words, I can indeed use `wrapper.vm.fetchData` to test the function, but how can I ensure that this function is actually called in the lifecycle I expected?

**Comment by wxsms** [comment]
I just read in the doc that:

> For UI components, we don't recommend aiming for complete line-based coverage, because it leads to too much focus on the internal implementation details of the components and could result in brittle tests.
> 
> Instead, we recommend writing tests that assert your component's public interface, and treat its internals as a black box. A single test case would assert that some input (user interaction or change of props) provided to the component results in the expected output (render result or emitted custom events).

Maybe I have a bad starting point in these cases (not treating its internals as a black box).  But I think that white box testing is also useful in some cases.

**Comment by bponomarenko** [comment]
> But I think that white box testing is also useful in some cases.

I have been working with Vue codebases for around 3-4 years, and in my experience such "granular" unit tests usually hard to maintain and they break to0 often without tangible reasons. Fixing those "false positives" takes more time than the actual value they bring.

But let me try to address your questions:
1. This is interesting challenge 🤔 But I think you don't even need Vue test utils to test that:
```js
import Vue from 'vue';
import TestComponent from 'src/components/test-component';

it('test', async () => {
  // Create component constructor
  const Comp = Vue.extend(TestComponent);
  const fetchDataSpy = jest.spyOn(Comp.options.methods, 'fetchData');
  
  expect(fetchDataSpy).not.toHaveBeenCalled();
  
  // Trigger component creation
  const instance = new Comp();
  
  expect(fetchDataSpy).toHaveBeenCalledTimes(1);
  
  // Explicitly mount component
  instance.$mount();
  
  expect(fetchDataSpy).toHaveBeenCalledTimes(2);
})
```
2. I guess example from the previous answer with slightly different checks should cover this used case too:
```js
// ...

// Trigger component creation
const instance = new Comp();
  
expect(fetchDataSpy).not.toHaveBeenCalled();
  
// Explicitly mount component
instance.$mount();
  
expect(fetchDataSpy).toHaveBeenCalledTimes(1);
```

**Comment by wxsms** [comment]
@bponomarenko Thank you very much for the kind answer and solution. You do solved my problem in a way that I have not consider yet. And I kind of agree your point about testing indeed. Good day.

**Comment by bponomarenko** [comment]
Happy to hear it help :) Good day to you too @wxsms
