### ISSUE TITLE
Cache output of Unit Test Compilation

### ISSUE THREAD

**Issue by 215699p** [vuejs/vue-test-utils#1970]
### Cache output of Unit Test Compilation

We currently use `@vue/cli-plugin-unit-mocha` to run our unit tests with `vue-cli-service test:unit`.

This works very well, except for the fact that the sources are compiled by webpack every time. Compiling with mochapack can take 30 to 60 seconds, while testing takes <10.

### Problem

We use the above approach to run our unit tests in our CI pipeline.

Ideally, we would like to be able to compile our code & testware independently of running the tests so that it could be cached in a docker layer for use in future CI builds, eliminating the need to compile on every CI run.

### Expected behaviour

Potential options:

A flag e.g. `vue-cli-service test:unit --compile` that triggers compilation only.
A flag e.g. `vue-cli-service test:unit --test` that triggers testing only & fails if no compiled files are present?

### Alternatives

I have tried to dig into the webpack magic that vue-test-utils is doing behind the scenes to see if I can determine the appropriate webpack command that would compile the unit test sources, but I haven't been able to figure that out.

If I can compile the same way that mochapack is compiling, and run the same way too (but independently!) this feature wouldn't be required.

Thanks for an awesome package!

**Comment by lmiller1990** [comment]
Hi!

Sorry for the slow reply. I'm mainly focused on v2 of this lib now, for Vue 3.

As for your caching idea, it's probably something you can do using webpack, but it wouldn't be a change you make in this repo. Test Utils is just handling `mount` and the wrapper API - no bundling etc.

I will close this since the feature request is outside the scope of this repo, I suppose this would fall under the mocha-test-unit plugin, or even just something you do in your own webpack config (seems very project specific).

Cool idea, please share if you come up with some caching solution to go faster.

**Comment by 215699p** [comment]
Hi, thanks for the reply - I will investigate further in the plugin you suggested.

I will follow up if I make progress.
