### ISSUE TITLE
Test manual watcher in vuex store

### ISSUE THREAD

**Issue by tehw0lf** [vuejs/vue-test-utils#1991]
### Subject of the issue

Hello, we've encountered an unexpected error in one of our route guard tests which tests the store's watchers.
The test adds a manual watcher using store.watch() and subsequently verifies that the watcher has been added to store?._watcherVM?._watchers.

When using vue 2.6.14 and vue-template-compiler 2.6.14, the test runs flawlessly.
The test fails when using vue 2.7.8 and vue-template-compiler 2.7.8.
 
During runtime we could verify that the watcher is added correctly, so it only seems to be an issue inside the test.

### Steps to reproduce

```ts
import Vuex, { Store } from 'vuex'
 
import { createLocalVue } from '@vue/test-utils'
 
const localVue = createLocalVue()
localVue.use(Vuex)
 
describe('my route guard', () => {
  it('should add a new watcher to store._watcherVM._watchers', () => {
    // Arrange
    const store: any = new Store({})
    const mockedTask = jest.fn()
    const mockedCallback = jest.fn()
 
    // Act
    const stopWatching = store.watch(
      (state, getters) => getters['getCurrentTask'],
      (newStoreValueValue) => {
        if (newStoreValueValue) {
          stopWatching()
          mockedCallback()
        }
      }
    )
 
    const storeWatchers: Array<any> = store?._watcherVM?._watchers
    storeWatchers[0].cb.call(this, mockedTask)
 
    // Assert
    expect(storeWatchers).toHaveLength(0) // Watcher was deregistered after execution
    expect(mockedCallback.mock.calls.length).toBe(1)
  })
})

```
### Expected behaviour

The test should pass with vue 2.7.8 and vue-template-compiler 2.7.8

### Actual behaviour

The test fails on 2.7.8, but works on 2.6.14

### Possible Solution

We have not found a workaround yet

**Comment by lmiller1990** [comment]
Hi! Forcing a watcher like does not seem ideal - as you said, it works perfectly in prod, so getting this test to pass isn't exactly meaningful - it's failing, **despite** the feature working correctly.

You are also accessing implementation details with `_watcherVM`. My guess is, most likely, Vue core changed something internally around reactivity in 2.7, which is why your test broke. Can you trigger the watch without forcing it via `_watcherVM`?

Also - I am not sure this is the right place for this bug report :thinking:  I don't see Test Utils in your test, except for importing `createLocalVue`, which is not actually used in your test. If you delete:

```js
import { createLocalVue } from '@vue/test-utils'
 
const localVue = createLocalVue()
localVue.use(Vuex)
```

I'm guessing the test still fails?

**Comment by tehw0lf** [comment]
Heya, thanks for the swift response. Indeed the test also fails when removing `createLocalVue`.

However, I've investigated the store again and found out that `_watcherVM` itself has a `_scope.effects` property which contains the watchers. I assume you're correct that the Vue behaviour has changed here and that the watcher array is now in `_scope.effects` instead of `_watchers`.

Thanks again and have a sunny day!
