### ISSUE TITLE
[Question] Is it possible to mock arbitrary imports?

### ISSUE THREAD

**Issue by robcresswell** [vuejs/vue-test-utils#301]
I understand that I can mock vue plugins, such as vue-router or vuex; but how would I mock a module that is imported and called within a component? For example, many of my components call to a custom logger via a JS module (just called `Log`). How would I mock this, and include it in the mounted component definition, to see if the functions had been called (and prevent them actually logging)?

I had hoped I could do something like:

```js
const Log = {
  error: jest.fn()
}

const component = mount(Component, {
  Log
})
```

in the same way you might mock `$router` 😄

**Comment by LinusBorg** [comment]
That's not within the scope of vue-test-utils, because it depends on the test runner and build setup you are running your tests with.

For Jest, you can look here: https://facebook.github.io/jest/docs/en/manual-mocks.html
For karma/mocha+webpack, you would use inject-loader, which vue-loader can do for you: https://vue-loader.vuejs.org/en/workflow/testing-with-mocks.html

**Comment by eddyerburgh** [comment]
If Log is imported from another file you can use [Jest manual mocks](https://facebook.github.io/jest/docs/en/manual-mocks.html#content), if you're using Jest. 

If not you could use babel-plugin-rewire, or inject-loader. I wrote a blog post on how to use those libraries—https://eddyerburgh.me/stub-file-dependencies-vue-unit-tests

**Comment by robcresswell** [comment]
@LinusBorg @eddyerburgh Thanks for the links and references, much appreciated
