### ISSUE TITLE
use with vue-resource throw error

### ISSUE THREAD

**Issue by mtdpcs** [vuejs/vue-test-utils#407]
### Version
1.0.0-beta.11

### Reproduction link
[https://github.com/mtdpcs/vue-test-util-ex](https://github.com/mtdpcs/vue-test-util-ex)

### Steps to reproduce
1. git clone https://github.com/mtdpcs/vue-test-util-ex.git
2. cd vue-test-util-ex npm install
3. npm run test

### What is expected?
unit passed 

### What is actually happening?
Cannot read property 'params' of undefined

---
in this project i install vue-resource and use 'Vue.url.params' to encode an obj to params,
when i run 'npm run dev' it works well , but when i run 'jest' i throw error.

**Comment by mtdpcs** [comment]
at App.vue i add this code 
`  import Vue from 'vue';
  import VueResource from 'vue-resource';
  Vue.use(VueResource);
  let encodeParams = Vue.url.params;`
then 'npm run test'  the unit passed

**Comment by eddyerburgh** [comment]
Thanks for the report, unfortunately this isn't a problem we can fix.

As you found, installing VueResource with `Vue.use` in the component before you access `Vue.url.params` solves the issue. This is because you are accessing the property on the Vue constructor, so the Vue constructor needs to have the plugin installed, otherwise it will try to access a property on an undefined value.

localVue is used as the base for the component instance that you're testing. If you install a plugin on a localVue, and pass localVue in the mounting options, the properties added by the plugin will be available on the component. So the component can access properties using this, but no properties are added to the base Vue constructor.

**Comment by mtdpcs** [comment]
how can i solve this problem? pleasre give me some help

**Comment by eddyerburgh** [comment]
You could refactor your component to access the property from the component instance:
```vue
<script>
export default {
  data(){
    return {
      params: {
        a: 123,
      }
    };
  },
  created(){
    console.log(this.url.params(this.params));
  },
}
</script>
```

And use a localVue that has VueResource installed, like you are in the test

**Comment by mtdpcs** [comment]
i install the vue-resource in config.js and use(vueResource) and improt config.js in main.js
`import Vue from 'vue'
import VueResource from 'vue-resource';
Vue.use(VueResource);`

and in App.spec.js i create loacalVue and use(VueResource)  too.
`import { shallow, createLocalVue } from 'vue-test-utils'
import VueResource from 'vue-resource';
import App from '../src/App'

const localVue = createLocalVue();
localVue.use(VueResource);
describe('App.vue', () => {
  it('use with vue-resource', () => {
    const wrapper = shallow(App, {localVue })
    const p = wrapper.findAll('p').at(0);
    expect(p.text()).toBe('hello word')
  })

})`

now i 'npm run' dev it works well, and  'npm run test' it throws errors.

**Comment by eddyerburgh** [comment]
Sorry, but from the reproduction you posted, this isn't a bug we're going to fix. If you have any more questions, please create a StackOverflow answer, or use the Vue discord channel. The issue tracker is reserved for bugs and feature requests
