### ISSUE TITLE
setProps does not update a data property

### ISSUE THREAD

**Issue by iraklisg** [vuejs/vue-test-utils#480]
### Version
1.0.0-beta.11

### Reproduction link
[https://github.com/iraklisg/vue-test-utils-example](https://github.com/iraklisg/vue-test-utils-example)

### Steps to reproduce
1. Clone the repo
2. `npm install`
3. `npm run test` or `npm run watch`

### What is expected?
The test should pass

### What is actually happening?
The `setProps` method does not update the data property

---
If we mount the component with options (`propsData`), instead of using the `setProps()` method, the test will pass green
```javascript
wrapper = mount(Foo, {
    propsData: {
        dataFoo: "foo"
    } 
});
```
```

<!-- generated by vue-issues. DO NOT REMOVE -->

**Comment by dennythecoder** [comment]
From the repo supplied, the component is doing this:
```javascript
export default {
    props: ['dataFoo'],
    data() {
        return {
            foo: this.dataFoo
        }
    }
};
```
Since `foo` is set when the component is created, it is not going to be reset when the prop is updated.  It'll be better for you to utilize a [computed property or update the data with a watcher](https://vuejs.org/v2/guide/computed.html), but this does not appear to be an issue with `vue-test-utils`.

**Comment by dennythecoder** [comment]
From the repo supplied, the component is doing this:
```javascript
export default {
    props: ['dataFoo'],
    data() {
        return {
            foo: this.dataFoo
        }
    }
};
```
Since `foo` is set when the component is created, it is not going to be reset when the prop is updated.  It'll be better for you to utilize a [computed property or update the data with a watcher](https://vuejs.org/v2/guide/computed.html), but this does not appear to be an issue with `vue-test-utils`.

**Comment by iraklisg** [comment]
@dennythecoder Hmm, maybe I am missing something here... 

I understand that `propsData` initializes the Vue instance with passed values (so the linked data property `foo` will be initialized with its value) but I would expect that `setProps()` will do the same by re-evaluating the Vue component. Besides, from the [vue test utils docs](https://vue-test-utils.vuejs.org/en/api/wrapper/setProps.html):
> **setProps(props)**
> Sets Wrapper vm props and forces update.

**Comment by dennythecoder** [comment]
@iraklisg, Using `setProps()` does not re-instantiate the component/vm/wrapper.  Instead, it's similar to when the component's parent (component or app) modifies the prop value and triggers an update.  _Update_ from the documentation appears to be referring to the normal reactivity in Vue.

`setProps` is found here:
https://github.com/vuejs/vue-test-utils/blob/dev/packages/test-utils/src/wrapper.js#L495

_forces update_ might be better worded though.  I don't see `$forceUpdate` being called.

**Comment by iraklisg** [comment]
Ok @dennythecoder it is clear now, thank you :+1:

**Comment by sandranrivas** [comment]
hey, after many hours of looking, I got an answer of how to workaround this.
https://stackoverflow.com/a/66029922/12237505
