### ISSUE TITLE
Improve document for setChecked(), setSelected() and setValue()

### ISSUE THREAD

**Issue by 38elements** [vuejs/vue-test-utils#700]
### Version
1.0.0-beta.18

### Reproduction link
[https://github.com/vuejs/vue-test-utils/tree/dev/docs](https://github.com/vuejs/vue-test-utils/tree/dev/docs)

### Steps to reproduce
Please See below links.

https://github.com/vuejs/vue-test-utils/blob/6dcfc4f5e88acc5aad903f5e2de619aa2bdb5ff0/docs/api/wrapper/setChecked.md

https://github.com/vuejs/vue-test-utils/blob/6dcfc4f5e88acc5aad903f5e2de619aa2bdb5ff0/docs/api/wrapper/setSelected.md

https://github.com/vuejs/vue-test-utils/blob/6dcfc4f5e88acc5aad903f5e2de619aa2bdb5ff0/docs/api/wrapper/setValue.md

### What is expected?
There are descriptions of reason why the functions is necessary in the document for setChecked(), setSelected() and setValue().

### What is actually happening?
The document for `setChecked()`, `setSelected()` and `setValue()` lacks the important points.
The important point is why the functions is necessary.
There was a problem which is not updating by `v-model`.
https://github.com/vuejs/vue-test-utils/issues/260#issuecomment-381694523
`setChecked()`, `setSelected()` and `setValue()` are added to resolve it.
I think the description of the problem should be added to the document for them.

**Comment by lmiller1990** [comment]
I personally don't see it as necessary to explain why it's needed - the idea of providing the helper functions is so that users don't need to understand the internals, and can focus on testing their components.

Although we could add something like:

"this is required to ensure `v-model` is correctly updated".

Another alternative would be adding a guide, perhaps called "Testing forms". It could show some common examples. The docs for `setValue` etc could then have a note linking to the guide.

**Comment by 38elements** [comment]
I did not mentioned "It is necessary to account internal.".

**Comment by 38elements** [comment]
I did not mentioned "It is necessary to account internal.".
You does not need to resolve this issue.
Other person will resolve it.
