### ISSUE TITLE
v-html icw .is() broken since beta18

### ISSUE THREAD

**Issue by aphofstede** [vuejs/vue-test-utils#743]
### Version
1.0.0-beta.18

### Reproduction link
[https://codesandbox.io/s/vx48ovm23](https://codesandbox.io/s/vx48ovm23)

### Steps to reproduce
Create a component that uses v-html directive and test that it .is() the right element type if the v-if directive evaluates to true

### What is expected?
is('div') returns true

### What is actually happening?
is('div') returns false

**Comment by eddyerburgh** [comment]
A quick fix is to use `$forceUpdate` to re render after you call setProps:

```js
wrapper.setProps({ propA: true })
wrapper.vm.$forceUpdate()
```

This was caused here—https://github.com/vuejs/vue-test-utils/pull/586/files#diff-68ebb4dd9f4503e2b26a1b1ac98d4fa2L60. Previously we were creating new root objects from propsData before passing it to the component.

The problem now is that when setProps reassigns the same object, the property getter returns early because it thinks the object isn't changing, so none of the dependencies are notified.

I think the best solution would be to call $forceUpdate if the prop that setProps is setting strictly equals the existing prop.
