### ISSUE TITLE
Children incorrectly rendered as false

### ISSUE THREAD

**Issue by moizang** [vuejs/vue-test-utils#857]
### Version
1.0.0-beta.21

### Reproduction link
[https://codesandbox.io/s/wnvpvr97ow](https://codesandbox.io/s/wnvpvr97ow)

### Steps to reproduce
Using Vuetify, I'm trying to test my usage of v-components :

**Snapshots** :
- No matter what I set between two v-component tags, it's always rendered as `false` in my snapshot when I shallowMount my component

**wrapper.find() doesn't seem to work on Vuetify components** : 
- Creating a component with a template featuring a v-component with a class prop set to "something"

- shallowMounting the new component

- Trying to perform a `wrapper.find('.something')` on my component

### What is expected?
- **Snapshot of v-component** -> expecting to see the values / or other components I used in my template between the v-component-stub tags

-  **wrapper.find('.v-component_class')** -> New wrapper with v-component

### What is actually happening?
- **Snapshot** : Always get `false` value between v-component stub tags

- **wrapper.find('.v-component_class')** -> empty wrapper

---
Both seemed to work in 1.0.0-beta.20

**Comment by eddyerburgh** [comment]
The problem with the child rendering false was because we were not handling functional components in the stub. I've fixed that in #860 .

The second problem you have is because you're using `shallowMount` instead of `mount`. shallowMount stubs all child components to render as a tag with the name ` `${registerd-component-name}-stub` `.  You can solve it by using `mount`:

```js
const wrapper = mount(TestComponent, { localVue });
const iconStyle = wrapper.find("icon-stub").element.style.color;
```
