### ISSUE TITLE
Add documentation on how to mock global components

### ISSUE THREAD

**Issue by ffxsam** [vuejs/vue-test-utils#894]
### What problem does this feature solve?
When testing components that include globally registered components, the test runner (in this case, Jest) throws warnings asking if the component was registered properly. As far as I can tell, the documentation doesn't explain how to mock global components.

### What does the proposed API look like?
N/A

**Comment by eddyerburgh** [comment]
The option you're looking for is [`stubs`](https://vue-test-utils.vuejs.org/api/options.html#stubs).

Do you have any suggestions for how we can make this clear? Maybe I guide on mocking components and properties?

**Comment by ffxsam** [comment]
Yes, 100%! I was surprised to not see a guide about stubbing components.

Thanks!

**Comment by 38elements** [comment]
I think it is better to close this issue.

**Comment by ffxsam** [comment]
After the documentation is added, you mean?

**Comment by 38elements** [comment]
If this issue is resolved, this issue should be closed.

**Comment by ffxsam** [comment]
The issue is "add documentation," so I would say the issue is resolved once the new docs on stubbing components are added.

**Comment by ffxsam** [comment]
It certainly can't hurt to have more examples in the guide. Why have an example for Vuex, but not something as basic as stubbing components?

**Comment by 38elements** [comment]
It is already documented.

Since it seems that he understand it, It seems that the cause is that I did not read the document.

https://github.com/vuejs/vue-test-utils/issues/894#issuecomment-410443231

Since the content of this issue is question, I think this issue should be posted in Stack Overflow, not here.

> Why have an example for Vuex, but not something as basic as stubbing components?

Since Vuex and stub are not related, I can not understand this comment.

**Comment by 38elements** [comment]
It is already documented.

Since it seems that he understand it, It seems that the cause is that I did not read the document.

https://github.com/vuejs/vue-test-utils/issues/894#issuecomment-410443231

Since the content of this issue seems to be question, I think this issue should be posted in Stack Overflow, not here.

> Why have an example for Vuex, but not something as basic as stubbing components?

Since Vuex and stub are not related, I can not understand this comment.

**Comment by 38elements** [comment]
It is already documented.

Since it seems that he understand it, It seems that the cause is that I did not read the document.

https://github.com/vuejs/vue-test-utils/issues/894#issuecomment-410443231

Since the content of this issue seems to be question, I think this issue should be posted in Stack Overflow, not here.

> Why have an example for Vuex, but not something as basic as stubbing components?

Since Vuex and stub are not related, I can not understand this comment.

**Comment by ffxsam** [comment]
I think you're misunderstanding my point in mentioning Vuex. The point was that the guide has specific how-to's, except basic things such as stubbing components.

@38elements Where is the example of stubbing components, did I miss it?

**Comment by 38elements** [comment]
It can not be the reason to add that be basic content or not.

>  Where is the example of stubbing components, did I miss it?

https://github.com/vuejs/vue-test-utils/issues/894#issuecomment-410423791

**Comment by 38elements** [comment]
It can not be the reason to add that it is basic content or not.

>  Where is the example of stubbing components, did I miss it?

https://github.com/vuejs/vue-test-utils/issues/894#issuecomment-410423791

**Comment by eddyerburgh** [comment]
It might not be obvious to someone that they should check the `options/stubs` section if they want to stub components. For example, @ffxsam read the documentation and couldn't find the information. 

We'll add a guide about stubbing component properties and components, even though they are already documented.

**Comment by 38elements** [comment]
IMHO,
I think he did not read document or did not know `stub` which is a term or both.
If he did not read document, it will not be resolved.
If he did not know `stub` which is a term, it is not the business of Vue Test Utils to explain `stub` which is a term.
Since  `stub` which is a term is the general term of test.

**Comment by 38elements** [comment]
IMHO,
I think he did not read document or did not know `stub` which is a term or both.
If he did not read document, it will not be resolved.
I think if he know `stub` which is a term, he can find stubs mouting option.
It is not the business of Vue Test Utils to explain `stub` which is a term
since  `stub` which is a term is the general term of test.

**Comment by ffxsam** [comment]
Ok, to clarify, since @38elements seems extremely bothered by this issue:

- I know what stubbing is.
- I'm relatively new to unit testing.
- I saw the API section, but I know API docs are generally for reference. I figured I would learn what I needed to learn from the Guides section, and I did not.

@38elements If you have nothing constructive to contribute, I'd recommend muting this issue. If nobody wants to update the guide to talk about stubbing components, that's totally fine (this is open source and free, so I have no expectations). If someone _wants_ to add a section to the guide, you certainly have no say over that.

**Comment by 38elements** [comment]
https://github.com/vuejs/vue-test-utils/issues/894#issuecomment-410559501
I think that this is a rude comment.
I do not accept this.
So, I will leave from this Vue Test Utils.
@eddyerburgh @kazupon and everyone
Thank you for your review and advice so far.
I hope that Vue Test Utils and Vue Fes 2018 will succeed.
Good luck!

**Comment by eddyerburgh** [comment]
I'm removing comments from this issue since they devolved into an argument. The plan is to add a guide to the documentation on stubbing components and mocking properties.

**Comment by 38elements** [comment]
@willvincent
Commenting after I said 'I will leave from here' is cowardly.
I am not interested in your personal values.
You have no contribute Vue Test Utils and I do not know you.
It looks just like you want to stand out.
I am annoying.
Would you please ignore me.

**Comment by 38elements** [comment]
I am back to Vue Test Utils, Because it seems @willvincent and @ffxsam leave from Vue Test Utils.
It seems they have never contributed to Vue Test Utils.
It seems they contribute to Vue Test Utils first time by leaving from Vue Test Utils and not being back to Vue Test Utils.
