### ISSUE TITLE
Props end up in `.attributes` are not having a proper casing

### ISSUE THREAD

**Issue by rayax86** [vuejs/vue-test-utils#954]
### Version
1.0.0-beta.20

### Reproduction link
[https://vue-test-utils.vuejs.org/api/wrapper/#attributes-key](https://vue-test-utils.vuejs.org/api/wrapper/#attributes-key)

### Steps to reproduce
Given I have a `Component.vue` that does not have any props defined:

```
const wrapper = shallowMount(Component, {
    propsData: {someProp: true},
});

console.log(wrapper.attributes());
```

### What is expected?
`{some-prop: true}` or `{someProp: true}` is printed

### What is actually happening?
`{someprop: true}` is printed

**Comment by eddyerburgh** [comment]
This is due to `setAttribute` used by Vue to set an elements attributes. `setAttribute` sets attribute names as lowercase according to the WhatWG spec:

>For attributes on HTML elements set by the HTML parser or by Element.setAttribute(), the local name will be lowercase.

We won't change this behavior in Vue Test Utils.

**Comment by rayax86** [comment]
Thanks for the reply (and your great work), @eddyerburgh !

However, I don't understand why you think the behaviour on this should be different from that in Vue. Vue does a translation for the attribute keys, from camelCase to kebab-case. So if I access `this.$attrs` in `Component.vue` in the given scenario, I will get `{some-prop: true}`. Even in `this.$el.attributes`, the key for this entry will be `some-prop` rather than `someprop`.
This inconsistent behaviour between Vue and Vue Test Utils can be annoying when trying to keep tests neat.

I am re-opening this issue. (No, I can't 😛, but I wish to)

**Comment by eddyerburgh** [comment]
Ok @rayax86 , let me look further into this

**Comment by eddyerburgh** [comment]
The behavior isn't different from Vue. `attributes` returns the DOM attributes of the root element of a wrapper. `$attrs` is the object passed in component data. `$attrs` can have camelCase keys, but HTML element attributes cannot be.

If you add a camelCase attribute to an element rendered by a Vue component you will see that it's registered in lower case. 

I can see that this can be surprising behavior in tests, but because it's how the DOM works Vue Test Utils will not translate DOM attribute keys to different casing.
