### ISSUE TITLE
How to handle dependencies import

### ISSUE THREAD

**Issue by FrancescoMussi** [vuejs/vue-test-utils#998]
### Version
1.0.0-beta.25

### Reproduction link
[https://codesandbox.io/s/01n76w1o9n](https://codesandbox.io/s/01n76w1o9n)

### Steps to reproduce
- Vue create fresh project
- Run the example test and check that passes correctly
- Import a dependency into the HelloWorld component (for example in my case: npm install --save epic-spinners)
- Run the example test again

### What is expected?
I expect the test to pass properly

### What is actually happening?
I get the error `SyntaxError: Unexpected token`

The error change with the dependency.
For example with epic-spinners I get:
`SyntaxError: Unexpected token import`

With vue-radial-progress I get 
`SyntaxError: Unexpected token <`

Depending on the source code of the package

---
In the beginning I thought I messed up something in my project.

But this behaviour is happening also on a fresh vue install.

Why is like that?

I tried to read everywhere for a solution but I didn't find it

**Comment by eddyerburgh** [comment]
The problem is that the imported packages are not being compiled correctly.

For example, Jest is configured to not compile node_modules by default. You can change the behavior by adding a `transformIgnorePatterns` option, to whitelist the modules that you need to compile:

```
{
  jest: {
    "transformIgnorePatterns": [
      "node_modules/(?!epic-spinners)"
    ]
  }
}
```

If you are using mocha-webpack, you must whitelist the modules in your webpack config.

**Comment by FrancescoMussi** [comment]
Thanks for the explanation.

It actually makes sense to not compile node modules.

Can I just bother you with just one final question?

What is then considered the best practice in these cases?
In situations where I am testing a component that imports a package?
I guess it's a pretty common scenario.

Is it possible to keep Jest configs as they are - not compiling node modules - and at the same time avoid errors messages while I am testing?

Thanks!

**Comment by eddyerburgh** [comment]
Unfortunately, the issue rests with package developers. 

For the last few years it's been a convention to export a compiled file that can be consumed without any compilation. Because of this, most build tools don't process node_modules by default. 

You could either create an issue in the repo of the packages that cause this behavior, or you will need to set your build tools to process the packages explicitly.

**Comment by FrancescoMussi** [comment]
Okay thanks for your time!

By using the configs you provided I fix the issue and tests are now passing properly.
